# Generated by Django 4.0.4 on 2022-06-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
