# Generated by Django 4.0.4 on 2022-06-30 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=125)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=125)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_received', models.IntegerField(blank=True, default=0, null=True)),
                ('inventory_shipped', models.IntegerField(blank=True, default=0, null=True)),
                ('inventory_on_hand', models.IntegerField(blank=True, default=0, null=True)),
                ('minimum_required', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField()),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
        ),
    ]
