# Generated by Django 4.0.4 on 2022-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_required',
            field=models.IntegerField(default=0),
        ),
    ]
