# Generated by Django 4.0.4 on 2022-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_inventory_on_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
