# Generated by Django 4.0.4 on 2022-06-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
