# Generated by Django 4.0.4 on 2022-06-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_created_at_product_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
